config/routes.rb
Rails.application.routes.draw do
    resources :students
    root 'students#index'
end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :find_student, only: [:show, :edit, :update, :destroy,]
  def index
  	@students = Student.all.order("created_at DESC") #New post is added to the top
  end

  def new
  	@student = Student.new
  end

  def create
  	@student = Student.new(post_params)
  	if @student.save
  		redirect_to @student
  	else
  		render 'new'
  	end
  end

  def show
  end

  def edit
  end

  def destroy
  	@student.destroy
  	redirect_to :action => :index
  end

  def update
  	@student = Student.find(params[:id])
  	if @student.update(post_params)
  		redirect_to @student
  	else
  		render 'edit'
  	end
  end

  private

  def find_student
  	@student = Student.find(params[:id])
  end

  def post_params
  	params.require(:student).permit(:Name, :Height, :Weight, :Color, :GPA)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Student Database</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>



	<%= link_to "Home", root_path %>
	<br>
	<%= link_to "Add New Student Information", new_student_path %>

<%= yield %> 

</body>
</html>

app/views/students/_form.html.erb
<%= form_for @student do |f| %>
	<%= f.label :Name %><br>
	<%= f.text_field :Name %> <br>
	<br>

	<%= f.label :Height %><br>
	<%= f.text_field :Height %> <br>
	<br>

	<%= f.label :Weight %><br>
	<%= f.text_field :Weight %> <br>
	<br>

	<%= f.label :Color %><br>
	<%= f.text_field :Color %> <br>
	<br>

	<%= f.label :GPA %><br>
	<%= f.text_field :GPA %> <br>
	<br>

	<%= f.submit %>

<% end %>

app/views/students/edit.html.erb
<h1> Edit Student Information </h1>

<%= render 'form' %>

app/views/students/index.html.erb
<% @students.each do |student| %>
	<h3><%= student.Name %></h3>
	<%= link_to "Profile", student %>
<% end %>

<div id="displayTable">
	<table border="1px solid red" align="center" class="InnerTable">
		<tr>
			<th>Name </th>
			<th>Height </th>
			<th>Weight </th>
			<th>GPA </th>
			<th>Color </th>
		</tr>
			<% @students.each do |student| %>
			<tr>
				<td><%= student.Name %> </td>
				<td><%= student.Height %> </td>
				<td><%= student.Weight %> </td>
				<td><%= student.GPA %> </td>
				<td><%= student.Color %> </td>
			</tr>
		<% end %>
	</table>
</div>

<div id="displayResult" style="vertical-align: text-bottom">
	<% @students.each do |p| %>

	<div class="displayResult1" style=" vertical-align: text-bottom;width: <%=p.Weight %>px; Height:<%= p.Height %>px; display: inline-block; border:1px solid #000;">
		<p style="color: <%= p.Color %>; text-align:center"> <%= p.Name %></p>
		<p style="text-align: center"> <%= p.GPA %></p>
	</div>

	<% end %>
</div>

app/views/students/new.html.erb
<h1> Student Information </h1>

<%= render 'form' %>

app/views/students/show.html.erb
<h1> <%= @student.Name %></h1>

<div>
	<%= @student.Height %>
	<%= @student.Weight %>
	<%= @student.Color %>
	<%= @student.GPA %>
</div>
<br>

<%= link_to 'EDIT', edit_student_path(@student) %>
<%= link_to 'DELETE', student_path(@student), method: :delete, data: {confirm: "Are you sure you want to DELETE your student information?"} %>